#!/bin/bash

echo "🔄 準備重啟開發伺服器..."
echo ""
echo "📋 執行步驟："
echo "1. 在運行開發伺服器的終端按 Ctrl+C"
echo "2. 執行以下命令："
echo ""
echo "   pnpm --filter web dev"
echo ""
echo "3. 等待看到: ✓ Ready in X.Xs"
echo ""
echo "=========================================="
echo "為什麼需要重啟？"
echo "=========================================="
echo "pdf-parse 已安裝，但 Next.js 還在使用舊的模組快取。"
echo "重啟後會載入新的 pdf-parse 模組，500 錯誤就會消失。"
echo ""
echo "=========================================="
echo "重啟後立即測試："
echo "=========================================="
echo "1. 訪問 http://localhost:3000/ask"
echo "2. 切換到「重點統整」Tab"
echo "3. 上傳 test-summary-upload.txt"
echo "4. 點擊「開始分析」"
echo ""
echo "✅ 應該看到成功日誌，不再有錯誤！"
