# fly.toml app configuration file generated for battle-ws on 2025-11-24T10:28:54+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'battle-ws'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  RUST_LOG = 'info'

# WebSocket 服務配置
[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
